# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clipMeshEK <- function(rmesh, rclipper, clipVolume, triangulate1, triangulate2, normals) {
    .Call(`_MeshesTools_clipMeshEK`, rmesh, rclipper, clipVolume, triangulate1, triangulate2, normals)
}

convexDecomposition <- function(rmesh, triangulate_in, triangulate_out) {
    .Call(`_MeshesTools_convexDecomposition`, rmesh, triangulate_in, triangulate_out)
}

distanceEK <- function(rmesh, points, triangulate) {
    .Call(`_MeshesTools_distanceEK`, rmesh, points, triangulate)
}

meshVolumeEK <- function(rmesh, triangulate) {
    .Call(`_MeshesTools_meshVolumeEK`, rmesh, triangulate)
}

meshAreaEK <- function(rmesh, triangulate) {
    .Call(`_MeshesTools_meshAreaEK`, rmesh, triangulate)
}

meshCentroidEK <- function(rmesh, triangulate) {
    .Call(`_MeshesTools_meshCentroidEK`, rmesh, triangulate)
}

