# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distanceEK <- function(rmesh, points, triangulate) {
    .Call(`_MeshesTools_distanceEK`, rmesh, points, triangulate)
}

meshVolumeEK <- function(rmesh, triangulate) {
    .Call(`_MeshesTools_meshVolumeEK`, rmesh, triangulate)
}

meshAreaEK <- function(rmesh, triangulate) {
    .Call(`_MeshesTools_meshAreaEK`, rmesh, triangulate)
}

